# NumPy

In [2]:
#import numpy library
import numpy as np

In [3]:
arr = np.random.rand(2,3,4)
arr

array([[[0.6189667 , 0.95514695, 0.67530719, 0.63897178],
        [0.06427125, 0.19588104, 0.1880573 , 0.42376327],
        [0.65704405, 0.43776863, 0.54232495, 0.71747558]],

       [[0.11647397, 0.47194714, 0.4075876 , 0.88064441],
        [0.53391144, 0.12239148, 0.70446607, 0.99467284],
        [0.98191734, 0.07113149, 0.13806291, 0.49812636]]])

In [4]:
type(arr)

numpy.ndarray

### NumPy - Array Attributes
#### Basics

In [5]:
#type of element in array
arr.dtype

dtype('float64')

In [6]:
# axis or dimension of array
arr.ndim

3

In [7]:
arr.shape

(2, 3, 4)

In [8]:
# size of array
arr.size

24

In [9]:
#size in bytes of element in array
arr.itemsize

8

In [10]:
arr.nbytes

192

## Array Creation

In [11]:
arr2 = np.random.rand(2,3,4)
arr2

array([[[0.76215635, 0.62101674, 0.55851139, 0.23789893],
        [0.91763289, 0.4120791 , 0.85129704, 0.78604442],
        [0.52537796, 0.13761199, 0.40844854, 0.92747484]],

       [[0.66890544, 0.6338254 , 0.7546398 , 0.625699  ],
        [0.25659201, 0.84627535, 0.14020072, 0.79437444],
        [0.97855293, 0.53219437, 0.52034994, 0.89169587]]])

In [12]:
zeros = np.zeros((2,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
full = np.full((2,3,4),7)
full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [14]:
ones = np.ones((2,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
#numpy.arrange(start, stop, step, dtype) 
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### NumPy Array vs List Size

In [16]:
l = [ i for i in range(0,100)]

In [17]:
np_arr = np.arange(100)
np_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
import sys
print(f"size of list - {sys.getsizeof(l)}")
print(f"size of numpy array - {sys.getsizeof(np_arr)}")

size of list - 904
size of numpy array - 504


In [19]:
#np_arr.size*np_arr.itemsize -> 100*4
np_arr.nbytes

400

#### NumPy Array

In [20]:
#numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

#### np.array or np.asarray
##### np.array creates copy of the object(copy = True) and does not reflect changes of orignal obj whereas np.asarray refelect changes

In [21]:
a = np.array([1,2,3,4,5])
print(f"orignal array - {a}")
np_array = np.array(a)
np_asarray = np.asarray(a)
a[1]=0
print("After changes at index 1=0")
print(f"np.array - {np_array}")
print(f"np.asarray - {np_asarray}")

orignal array - [1 2 3 4 5]
After changes at index 1=0
np.array - [1 2 3 4 5]
np.asarray - [1 0 3 4 5]


### Indexing, Slicing, Updating

In [22]:
arr

array([[[0.6189667 , 0.95514695, 0.67530719, 0.63897178],
        [0.06427125, 0.19588104, 0.1880573 , 0.42376327],
        [0.65704405, 0.43776863, 0.54232495, 0.71747558]],

       [[0.11647397, 0.47194714, 0.4075876 , 0.88064441],
        [0.53391144, 0.12239148, 0.70446607, 0.99467284],
        [0.98191734, 0.07113149, 0.13806291, 0.49812636]]])

In [23]:
#Indexing
arr[0][0][2]

0.675307189692305

In [24]:
# accessing and updating element
arr[0][0][0] =1
arr

array([[[1.        , 0.95514695, 0.67530719, 0.63897178],
        [0.06427125, 0.19588104, 0.1880573 , 0.42376327],
        [0.65704405, 0.43776863, 0.54232495, 0.71747558]],

       [[0.11647397, 0.47194714, 0.4075876 , 0.88064441],
        [0.53391144, 0.12239148, 0.70446607, 0.99467284],
        [0.98191734, 0.07113149, 0.13806291, 0.49812636]]])

In [25]:
# slicing
arr[1][1]

array([0.53391144, 0.12239148, 0.70446607, 0.99467284])

In [26]:
arr[1][1:][0,1]

0.12239148473381367

In [27]:
arr[1][1:,1:]

array([[0.12239148, 0.70446607, 0.99467284],
       [0.07113149, 0.13806291, 0.49812636]])

In [28]:
arr[1][1:,2:]

array([[0.70446607, 0.99467284],
       [0.13806291, 0.49812636]])

In [29]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])

In [30]:
a+b

array([[ 3,  6,  9, 12],
       [ 4,  8, 11, 14],
       [12, 24, 45, 11]])

### Broadcasting

The term broadcasting refers to how numpy treats arrays with different Dimension during arithmetic operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes. 

In [31]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])
a*b

array([[  2,   8,  18,  32],
       [  4,  16,  30,  48],
       [ 20,  80, 234,  24]])

In [32]:
a = np.ones((2,2,2))
a

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [33]:
b=np.random.rand(1,2)
b

array([[0.66578775, 0.64918897]])

In [34]:
a*b

array([[[0.66578775, 0.64918897],
        [0.66578775, 0.64918897]],

       [[0.66578775, 0.64918897],
        [0.66578775, 0.64918897]]])

In [35]:
c= np.ones((5,1))
c

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [36]:
d= np.ones((1,6))
d

array([[1., 1., 1., 1., 1., 1.]])

c (5x1) and d (1x6) can be broadcasted 

In [37]:
print(c+d)
print(f"shape of array {(c+d).shape}")

[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]
shape of array (5, 6)


In [38]:
f= np.ones((3,2,2,3))
g = np.ones((2,3))

In [39]:
print((f+g).shape)

(3, 2, 2, 3)


A      (4d array):  8 x 1 x 6 x 1 <br>
B      (3d array):      7 x 1 x 5 <br>
Result (4d array):  8 x 7 x 6 x 5

## NumPy - Iterating over arrays
NumPy package contains an iterator object numpy.nditer

In [69]:
arr = np.arange(0,100,5).reshape(4,5)
arr

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [54]:
for i in arr:
    print(i,end="")

[ 0  5 10 15 20][25 30 35 40 45][50 55 60 65 70][75 80 85 90 95]

In [55]:
for i in np.nditer(arr):
    print(i,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 

Order of the iteration doesn't follow any special ordering like row-major or column-order. However, it is intended to match the memory layout of the array.

In [56]:
arr_t = arr.T
arr_t

array([[ 0, 25, 50, 75],
       [ 5, 30, 55, 80],
       [10, 35, 60, 85],
       [15, 40, 65, 90],
       [20, 45, 70, 95]])

In [59]:
for i in np.nditer(arr_t):
    print(i,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 

### Order of Iteration
F-style order - column wise <br>
C-style order - row wise


In [60]:
for i in np.nditer(arr_t,order='F'):
    print(i,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 

In [61]:
for i in np.nditer(arr_t,order ='C'):
    print(i,end=" ")

0 25 50 75 5 30 55 80 10 35 60 85 15 40 65 90 20 45 70 95 

### Array Modification
The nditer object has another optional parameter called op_flags. Its default value is read-only, but can be set to read-write or write-only mode. This will enable modifying array elements using this iterator.

In [73]:
for i in np.nditer(arr,op_flags=['readwrite']):
    i[...]=i*2
    print(i,end=" ")

0 20 40 60 80 100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 

### Broadcasting Iteration
If two arrays are broadcastable, a combined nditer object is able to iterate upon them concurrently. Assuming that an array a has dimension 3X4, and there is another array b of dimension 1X4, the iterator of following type is used (array b is broadcast to size of a).

In [75]:
a= np.arange(1,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
b= np.full((4),10)
b

array([10, 10, 10, 10])

In [78]:
for x,y in np.nditer([a,b]):
    print( x+y , end=' ')

10 11 12 13 14 15 16 17 18 19 20 21 

## NumPy - Mathematical Functions
Numpy contains a large number of mathematical functions which can be used to perform various mathematical operations. The mathematical functions include trigonometric functions, arithmetic functions, and functions for handling complex numbers.



## Numpy statistical functions
#### SAPLEM

In [79]:
sqrt = np.sqrt(36)
sqrt

6.0

In [80]:
np.abs(-2)

2

In [81]:
np.power(2,3)

8

In [82]:
np.log(100)

4.605170185988092

In [83]:
np.exp([1,2,3])

array([ 2.71828183,  7.3890561 , 20.08553692])

In [84]:
np.min(a)

0

In [85]:
np.max(a)

11

In [86]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
a

array([[ 2, 10, 20],
       [80, 43, 31],
       [22, 43, 10]])

In [87]:
print("\nThe minimum element among the rows of array",np.amin(a,0))  
print("The maximum element among the rows of array",np.amax(a,0))    
print("\nThe minimum element among the columns of array",np.amin(a,1))  
print("The maximum element among the columns of array",np.amax(a,1))  


The minimum element among the rows of array [ 2 10 10]
The maximum element among the rows of array [80 43 31]

The minimum element among the columns of array [ 2 31 10]
The maximum element among the columns of array [20 80 43]


### Insertion

In [88]:
zeros = np.zeros((7))
zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [89]:
np.append(zeros,[1,1])

array([0., 0., 0., 0., 0., 0., 0., 1., 1.])

In [90]:
np.insert(zeros,3,3)

array([0., 0., 0., 3., 0., 0., 0., 0.])

### Deletion

In [92]:
data = np.random.rand(2,3,4)
data

array([[[0.95859516, 0.59256458, 0.23019406, 0.36349483],
        [0.95835672, 0.71622579, 0.61913258, 0.21470265],
        [0.3729762 , 0.2108884 , 0.73085821, 0.38025093]],

       [[0.69699393, 0.33363207, 0.75522261, 0.41446112],
        [0.6578325 , 0.0928681 , 0.87149232, 0.26602887],
        [0.82538007, 0.51415214, 0.30997092, 0.74679515]]])

In [93]:
np.delete(data,0,axis=1)

array([[[0.95835672, 0.71622579, 0.61913258, 0.21470265],
        [0.3729762 , 0.2108884 , 0.73085821, 0.38025093]],

       [[0.6578325 , 0.0928681 , 0.87149232, 0.26602887],
        [0.82538007, 0.51415214, 0.30997092, 0.74679515]]])

## Saving

In [94]:
np.save("new array",data)
t = np.load("new array.npy")
t

array([[[0.95859516, 0.59256458, 0.23019406, 0.36349483],
        [0.95835672, 0.71622579, 0.61913258, 0.21470265],
        [0.3729762 , 0.2108884 , 0.73085821, 0.38025093]],

       [[0.69699393, 0.33363207, 0.75522261, 0.41446112],
        [0.6578325 , 0.0928681 , 0.87149232, 0.26602887],
        [0.82538007, 0.51415214, 0.30997092, 0.74679515]]])