# NumPy

In [2]:
#import numpy library
import numpy as np

In [3]:
arr = np.random.rand(2,3,4)
arr

array([[[0.17746543, 0.96857614, 0.01738588, 0.55342423],
        [0.59961796, 0.21465042, 0.37390348, 0.06352661],
        [0.5345501 , 0.94567372, 0.72077933, 0.08870645]],

       [[0.18820026, 0.7196094 , 0.969627  , 0.26649855],
        [0.43193511, 0.77051314, 0.26580986, 0.15060651],
        [0.35495663, 0.682798  , 0.29842213, 0.03272479]]])

In [4]:
type(arr)

numpy.ndarray

### NumPy - Array Attributes
#### Basics

In [5]:
#type of element in array
arr.dtype

dtype('float64')

In [6]:
# axis or dimension of array
arr.ndim

3

In [7]:
arr.shape

(2, 3, 4)

In [8]:
# size of array
arr.size

24

In [9]:
#size in bytes of element in array
arr.itemsize

8

In [10]:
arr.nbytes

192

## Array Creation

In [11]:
arr2 = np.random.rand(2,3,4)
arr2

array([[[0.92058437, 0.31266414, 0.45934472, 0.41511736],
        [0.08669698, 0.00341752, 0.43816371, 0.44191738],
        [0.73326848, 0.75590586, 0.34821611, 0.90931552]],

       [[0.71159705, 0.65192629, 0.39737857, 0.22860567],
        [0.66272609, 0.71941685, 0.98470115, 0.63587404],
        [0.29370519, 0.76088766, 0.5596954 , 0.813136  ]]])

In [12]:
zeros = np.zeros((2,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
full = np.full((2,3,4),7)
full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [14]:
ones = np.ones((2,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
#numpy.arrange(start, stop, step, dtype) 
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### NumPy Array vs List Size

In [16]:
l = [ i for i in range(0,100)]

In [17]:
np_arr = np.arange(100)
np_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
import sys
print(f"size of list - {sys.getsizeof(l)}")
print(f"size of numpy array - {sys.getsizeof(np_arr)}")

size of list - 904
size of numpy array - 504


In [19]:
#np_arr.size*np_arr.itemsize -> 100*4
np_arr.nbytes

400

#### NumPy Array

In [20]:
#numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

#### np.array or np.asarray
##### np.array creates copy of the object(copy = True) and does not reflect changes of orignal obj whereas np.asarray refelect changes

In [21]:
a = np.array([1,2,3,4,5])
print(f"orignal array - {a}")
np_array = np.array(a)
np_asarray = np.asarray(a)
a[1]=0
print("After changes at index 1=0")
print(f"np.array - {np_array}")
print(f"np.asarray - {np_asarray}")

orignal array - [1 2 3 4 5]
After changes at index 1=0
np.array - [1 2 3 4 5]
np.asarray - [1 0 3 4 5]


### Indexing, Slicing, Updating

In [22]:
arr

array([[[0.17746543, 0.96857614, 0.01738588, 0.55342423],
        [0.59961796, 0.21465042, 0.37390348, 0.06352661],
        [0.5345501 , 0.94567372, 0.72077933, 0.08870645]],

       [[0.18820026, 0.7196094 , 0.969627  , 0.26649855],
        [0.43193511, 0.77051314, 0.26580986, 0.15060651],
        [0.35495663, 0.682798  , 0.29842213, 0.03272479]]])

In [23]:
#Indexing
arr[0][0][2]

0.017385875319153254

In [24]:
# accessing and updating element
arr[0][0][0] =1
arr

array([[[1.        , 0.96857614, 0.01738588, 0.55342423],
        [0.59961796, 0.21465042, 0.37390348, 0.06352661],
        [0.5345501 , 0.94567372, 0.72077933, 0.08870645]],

       [[0.18820026, 0.7196094 , 0.969627  , 0.26649855],
        [0.43193511, 0.77051314, 0.26580986, 0.15060651],
        [0.35495663, 0.682798  , 0.29842213, 0.03272479]]])

In [25]:
# slicing
arr[1][1]

array([0.43193511, 0.77051314, 0.26580986, 0.15060651])

In [26]:
arr[1][1:][0,1]

0.7705131359359886

In [27]:
arr[1][1:,1:]

array([[0.77051314, 0.26580986, 0.15060651],
       [0.682798  , 0.29842213, 0.03272479]])

In [28]:
arr[1][1:,2:]

array([[0.26580986, 0.15060651],
       [0.29842213, 0.03272479]])

In [29]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])

In [30]:
a+b

array([[ 3,  6,  9, 12],
       [ 4,  8, 11, 14],
       [12, 24, 45, 11]])

### Broadcasting

The term broadcasting refers to how numpy treats arrays with different Dimension during arithmetic operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes. 

In [34]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])
a*b

array([[  2,   8,  18,  32],
       [  4,  16,  30,  48],
       [ 20,  80, 234,  24]])

In [35]:
a

array([[ 1,  2,  3,  4],
       [ 2,  4,  5,  6],
       [10, 20, 39,  3]])

In [39]:
a.reshape(2,3,2)

ValueError: operands could not be broadcast together with shapes (2,3,2) (4,) 

In [38]:
a

array([[ 1,  2,  3,  4],
       [ 2,  4,  5,  6],
       [10, 20, 39,  3]])